version: 0.2

phases:
  pre_build:
    commands:
      - echo [$(date)] Pre-build started
      - pip install --upgrade --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - echo [$(date)] Pre-build finished
  build:
    commands:
      - echo [$(date)] Build started
      - echo [$(date)] Building SAM template
      - |
        sam package \
          --template-file ./cloudformation/template.yaml \
          --output-template-file ./packaged.yml \
          --s3-bucket $ARTIFACTS_BUCKET
      - echo [$(date)] Build completed
  post_build:
    commands:
      - echo [$(date)] Post build starting
      - echo [$(date)] Post build finished

artifacts:
  files:
    - packaged.yml
